name: iOS Unsigned Build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install
          npm install -g expo-cli

      - name: Clean existing ios directory
        run: |
          rm -rf ios/
          rm -rf android/

      - name: Generate native iOS files
        run: |
          npx expo prebuild --platform ios --no-install
          echo "Generated iOS files:"
          ls -la ios/

      - name: Pod Install
        run: |
          cd ios
          rm -f Podfile.lock
          pod install --repo-update

      - name: Build Unsigned IPA
        run: |
          cd ios
          xcodebuild -scheme FoodTime -workspace FoodTime.xcworkspace -configuration Release clean archive \
            -archivePath "build/FoodTime.xcarchive" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Create IPA
        run: |
          cd ios
          mkdir -p build/Payload
          mv build/FoodTime.xcarchive/Products/Applications/FoodTime.app build/Payload/FoodTime.app
          cd build
          zip -r FoodTime.ipa Payload/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: 'Release ${{ github.ref_name }}'
          files: ios/build/FoodTime.ipa
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}